name: vbg_basics
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  - python-dotenv
  - jupyterlab
  - numpy
  - pandas
  - requests
  - ipywidgets
  - matplotlib
  - chromadb
  - pip:
    - plotly
    - beautifulsoup4
    - gradio
    - ollama
    - openai
    - feedparser
    - lxml
    - gradio_client
    - fastapi
    - uvicorn
    - langchain
    - langchain-community
    - langchain-core
    - langchain-ollama